package com.seascape.roomstar.domain;

// Generated Sep 14, 2013 1:58:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Long addressId;
	private long addressTypeId;
	private long customerId;
	private String line1;
	private String line2;
	private String co;
	private String city;
	private String state;
	private String zipcode;
	private String country;
	private String orgName;
	private String contactPhone;
	private String email;

	public Address() {
	}

	public Address(long addressTypeId, long customerId, String line1,
			String city, String state) {
		this.addressTypeId = addressTypeId;
		this.customerId = customerId;
		this.line1 = line1;
		this.city = city;
		this.state = state;
	}

	public Address(long addressTypeId, long customerId, String line1,
			String line2, String co, String city, String state, String zipcode,
			String country, String orgName, String contactPhone, String email) {
		this.addressTypeId = addressTypeId;
		this.customerId = customerId;
		this.line1 = line1;
		this.line2 = line2;
		this.co = co;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.orgName = orgName;
		this.contactPhone = contactPhone;
		this.email = email;
	}

	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public long getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(long addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	public String getCo() {
		return this.co;
	}

	public void setCo(String co) {
		this.co = co;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
