package com.seascape.roomstar.domain;

// Generated Sep 12, 2013 12:46:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * AddressType generated by hbm2java
 */
public class AddressType implements java.io.Serializable {

	private Long addressTypeId;
	private String addressTypeDesc;

	public AddressType() {
	}

	public AddressType(String addressTypeDesc) {
		this.addressTypeDesc = addressTypeDesc;
	}

	public Long getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(Long addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public String getAddressTypeDesc() {
		return this.addressTypeDesc;
	}

	public void setAddressTypeDesc(String addressTypeDesc) {
		this.addressTypeDesc = addressTypeDesc;
	}

}
