package com.seascape.roomstar.domain;

// Generated Sep 7, 2013 1:38:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * Amentity generated by hbm2java
 */
public class Amentity implements java.io.Serializable {

	private Long amentityId;
	private String name;
	private Integer totalQuantityAvailable;

	public Amentity() {
	}

	public Amentity(String name, Integer totalQuantityAvailable) {
		this.name = name;
		this.totalQuantityAvailable = totalQuantityAvailable;
	}

	public Long getAmentityId() {
		return this.amentityId;
	}

	public void setAmentityId(Long amentityId) {
		this.amentityId = amentityId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getTotalQuantityAvailable() {
		return this.totalQuantityAvailable;
	}

	public void setTotalQuantityAvailable(Integer totalQuantityAvailable) {
		this.totalQuantityAvailable = totalQuantityAvailable;
	}

}
