package com.seascape.roomstar.domain;

// Generated Sep 14, 2013 1:58:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * RateType generated by hbm2java
 */
public class RateType implements java.io.Serializable {

	private Long rateTypeId;
	private String name;
	private double value;

	public RateType() {
	}

	public RateType(String name, double value) {
		this.name = name;
		this.value = value;
	}

	public Long getRateTypeId() {
		return this.rateTypeId;
	}

	public void setRateTypeId(Long rateTypeId) {
		this.rateTypeId = rateTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
