package com.seascape.roomstar.domain;

// Generated Sep 12, 2013 12:46:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReservationAmentity generated by hbm2java
 */
public class ReservationAmentity implements java.io.Serializable {

	private ReservationAmentityId id;

	public ReservationAmentity() {
	}

	public ReservationAmentity(ReservationAmentityId id) {
		this.id = id;
	}

	public ReservationAmentityId getId() {
		return this.id;
	}

	public void setId(ReservationAmentityId id) {
		this.id = id;
	}

}
