package com.seascape.roomstar.domain;

// Generated Sep 12, 2013 12:46:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Long reservationId;
	private long customerId;
	private long roomTypeId;
	private long rateTypeId;
	private String voucherCode;
	private String rewardsNumber;
	private String notes;
	private String creationDate;
	private String createdBy;
	private String lastUpdatedDate;
	private String lastUpdatedBy;
	private String checkInDate;
	private String checkOutDate;
	private Integer nights;

	public Reservation() {
	}

	public Reservation(long customerId, long roomTypeId, long rateTypeId) {
		this.customerId = customerId;
		this.roomTypeId = roomTypeId;
		this.rateTypeId = rateTypeId;
	}

	public Reservation(long customerId, long roomTypeId, long rateTypeId,
			String voucherCode, String rewardsNumber, String notes,
			String creationDate, String createdBy, String lastUpdatedDate,
			String lastUpdatedBy, String checkInDate, String checkOutDate,
			Integer nights) {
		this.customerId = customerId;
		this.roomTypeId = roomTypeId;
		this.rateTypeId = rateTypeId;
		this.voucherCode = voucherCode;
		this.rewardsNumber = rewardsNumber;
		this.notes = notes;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.checkInDate = checkInDate;
		this.checkOutDate = checkOutDate;
		this.nights = nights;
	}

	public Long getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Long reservationId) {
		this.reservationId = reservationId;
	}

	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public long getRoomTypeId() {
		return this.roomTypeId;
	}

	public void setRoomTypeId(long roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	public long getRateTypeId() {
		return this.rateTypeId;
	}

	public void setRateTypeId(long rateTypeId) {
		this.rateTypeId = rateTypeId;
	}

	public String getVoucherCode() {
		return this.voucherCode;
	}

	public void setVoucherCode(String voucherCode) {
		this.voucherCode = voucherCode;
	}

	public String getRewardsNumber() {
		return this.rewardsNumber;
	}

	public void setRewardsNumber(String rewardsNumber) {
		this.rewardsNumber = rewardsNumber;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getCheckInDate() {
		return this.checkInDate;
	}

	public void setCheckInDate(String checkInDate) {
		this.checkInDate = checkInDate;
	}

	public String getCheckOutDate() {
		return this.checkOutDate;
	}

	public void setCheckOutDate(String checkOutDate) {
		this.checkOutDate = checkOutDate;
	}

	public Integer getNights() {
		return this.nights;
	}

	public void setNights(Integer nights) {
		this.nights = nights;
	}

}
