package com.seascape.roomstar.domain;

// Generated Sep 14, 2013 1:58:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoomType generated by hbm2java
 */
public class RoomType implements java.io.Serializable {

	private Long roomTypeId;
	private String name;
	private String description;

	public RoomType() {
	}

	public RoomType(String name) {
		this.name = name;
	}

	public RoomType(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Long getRoomTypeId() {
		return this.roomTypeId;
	}

	public void setRoomTypeId(Long roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
