package com.seascape.roomstar.domain;

// Generated Sep 14, 2013 1:58:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoomInventoryStatus generated by hbm2java
 */
public class RoomInventoryStatus implements java.io.Serializable {

	private Long roomInventoryStatusId;
	private long roomInventoryId;
	private long roomStatusTypeId;
	private String creationDate;
	private String createdBy;

	public RoomInventoryStatus() {
	}

	public RoomInventoryStatus(long roomInventoryId, long roomStatusTypeId,
			String creationDate, String createdBy) {
		this.roomInventoryId = roomInventoryId;
		this.roomStatusTypeId = roomStatusTypeId;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
	}

	public Long getRoomInventoryStatusId() {
		return this.roomInventoryStatusId;
	}

	public void setRoomInventoryStatusId(Long roomInventoryStatusId) {
		this.roomInventoryStatusId = roomInventoryStatusId;
	}

	public long getRoomInventoryId() {
		return this.roomInventoryId;
	}

	public void setRoomInventoryId(long roomInventoryId) {
		this.roomInventoryId = roomInventoryId;
	}

	public long getRoomStatusTypeId() {
		return this.roomStatusTypeId;
	}

	public void setRoomStatusTypeId(long roomStatusTypeId) {
		this.roomStatusTypeId = roomStatusTypeId;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
