package com.seascape.roomstar.domain;

// Generated Sep 12, 2013 12:46:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoomInventory generated by hbm2java
 */
public class RoomInventory implements java.io.Serializable {

	private long roomInventoryId;
	private long roomTypeId;
	private String displayNumber;
	private String displayName;
	private Integer floorLevel;
	private Long adjoiningRoom;

	public RoomInventory() {
	}

	public RoomInventory(long roomInventoryId, long roomTypeId) {
		this.roomInventoryId = roomInventoryId;
		this.roomTypeId = roomTypeId;
	}

	public RoomInventory(long roomInventoryId, long roomTypeId,
			String displayNumber, String displayName, Integer floorLevel,
			Long adjoiningRoom) {
		this.roomInventoryId = roomInventoryId;
		this.roomTypeId = roomTypeId;
		this.displayNumber = displayNumber;
		this.displayName = displayName;
		this.floorLevel = floorLevel;
		this.adjoiningRoom = adjoiningRoom;
	}

	public long getRoomInventoryId() {
		return this.roomInventoryId;
	}

	public void setRoomInventoryId(long roomInventoryId) {
		this.roomInventoryId = roomInventoryId;
	}

	public long getRoomTypeId() {
		return this.roomTypeId;
	}

	public void setRoomTypeId(long roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	public String getDisplayNumber() {
		return this.displayNumber;
	}

	public void setDisplayNumber(String displayNumber) {
		this.displayNumber = displayNumber;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Integer getFloorLevel() {
		return this.floorLevel;
	}

	public void setFloorLevel(Integer floorLevel) {
		this.floorLevel = floorLevel;
	}

	public Long getAdjoiningRoom() {
		return this.adjoiningRoom;
	}

	public void setAdjoiningRoom(Long adjoiningRoom) {
		this.adjoiningRoom = adjoiningRoom;
	}

}
