package com.seascape.roomstar.domain;

// Generated Sep 12, 2013 12:46:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoomAmentity generated by hbm2java
 */
public class RoomAmentity implements java.io.Serializable {

	private Long roomAmentityId;
	private long roomInventoryId;
	private long amentityId;

	public RoomAmentity() {
	}

	public RoomAmentity(long roomInventoryId, long amentityId) {
		this.roomInventoryId = roomInventoryId;
		this.amentityId = amentityId;
	}

	public Long getRoomAmentityId() {
		return this.roomAmentityId;
	}

	public void setRoomAmentityId(Long roomAmentityId) {
		this.roomAmentityId = roomAmentityId;
	}

	public long getRoomInventoryId() {
		return this.roomInventoryId;
	}

	public void setRoomInventoryId(long roomInventoryId) {
		this.roomInventoryId = roomInventoryId;
	}

	public long getAmentityId() {
		return this.amentityId;
	}

	public void setAmentityId(long amentityId) {
		this.amentityId = amentityId;
	}

}
